task_type: sequence_classification
corpus: frenchmedmcqa
task: cls
subset: default
lang: fr

hf_loader: data_loaders_hf/FrenchMedMCQA.py
label_column: number_correct_answers
text_columns: [question, answer_a, answer_b, answer_c, answer_d, answer_e]
text_separator: sep_token
max_position_embeddings: 512
fewshot: 1.0
dedup:
  scope: cascade
  drop_empty: false
  drop_all_negative: false

metrics: "f1"
direction: ["max", "maximize"]

search_space:
  learning_rate: tune.loguniform(1e-6, 1e-4)
  num_train_epochs: tune.qrandint(10, 40, 10)
  gradient_accumulation_steps: tune.randint(1, 5)
  weight_decay: tune.uniform(0, .5)
  warmup_ratio: tune.uniform(0, .5)
  dropout: tune.uniform(0, .5)
fixed:
  per_device_train_batch_size: 16
scheduler:
  reduction_factor: 2
  grace_period: 3
  max_t: 100
n_trials: 20
