task_type: token_classification
corpus: e3c
task: ner
subset: English_temporal
lang: en

hf_loader: data_loaders_hf/E3C.py
label_column: ner_tags
max_position_embeddings: 512
fewshot: 1.0
dedup:
  scope: cascade
  drop_empty: false
  drop_all_negative: true

metrics: "f1"
direction: ["max", "maximize"]

search_space:
  learning_rate: tune.loguniform(1e-6, 1e-4)
  per_device_train_batch_size: tune.qrandint(8, 16, 8)
  num_train_epochs: tune.qrandint(10, 50, 5)
  weight_decay: tune.uniform(0, .5)
  warmup_ratio: tune.uniform(0, .5)
  dropout: tune.uniform(0, .5)
fixed: {}
scheduler:
  reduction_factor: 2
  grace_period: 2
  max_t: 100
n_trials: 20
